server:
  port: 8763

spring:
  application:
    name: hello-sc-alibaba-express

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.179:8848
        namespace: public
        username: nacos
        password: nacos